-- Migration: 0001_create_leads
-- Creates the core leads table for the CM Funnel

CREATE TABLE IF NOT EXISTS leads (
  id              TEXT PRIMARY KEY,          -- UUID generated by the Worker
  first_name      TEXT,
  last_name       TEXT,
  email           TEXT,
  phone           TEXT,
  qualifier_one   TEXT,
  qualifier_two   TEXT,
  additional_info TEXT,
  consent         INTEGER NOT NULL DEFAULT 0, -- 0 = false, 1 = true
  current_step    INTEGER NOT NULL DEFAULT 1,
  completed       INTEGER NOT NULL DEFAULT 0, -- 0 = false, 1 = true

  -- UTM tracking
  utm_source      TEXT,
  utm_medium      TEXT,
  utm_campaign    TEXT,
  utm_content     TEXT,
  utm_term        TEXT,

  -- Request metadata
  ip_address      TEXT,
  user_agent      TEXT,

  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);

-- Index for fast lookup by email (deduplication, CRM sync)
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads (email);

-- Index for filtering by completion status
CREATE INDEX IF NOT EXISTS idx_leads_completed ON leads (completed);

-- Index for UTM campaign analysis
CREATE INDEX IF NOT EXISTS idx_leads_utm_campaign ON leads (utm_campaign);
